### ISSUE TITLE
Bug (Error) Report

### ISSUE THREAD

**Issue by yan-libo** [levimcclenny/SA-PINNs#1]
Hi @levimcclenny  

A very large weight factor (**100**) is used in the simulations:

i.e. `u_weights = tf.Variable(100*tf.random.uniform([N0, 1]))` 

However, If we set the weight factor to **1.0** (default value) 

This proposed Self-Adaptive PINN will **NOT** work any more, see the output figure from AC example with the following modification:
`u_weights = tf.Variable(1*tf.random.uniform([N0, 1]))`

![grafik](https://user-images.githubusercontent.com/79023476/107860577-36b92e00-6e40-11eb-95f6-f7bce2ae1ce2.png)

at t = 0.99, obviouly, the numerical error is (very) large.

Best
Libo

**Comment by levimcclenny** [comment]
Yes this initialization question is one we discuss in the paper. However compared to the baseline PINN it is still a marked improvement. I don't believe I would classify this as a "bug", just a research questions as to what the scale of the weight initialization needs to be. Additionally, the `u_weights` vector is only for the weights on the `t=0` boundary, so we can see that it fits the earlier `u` solution well from your plot at `t=0.25`. But the initialization does effect the later error at `t=.99`. 

Also I would be curious as to how many iterations this was ran at. That detail is absent in your description. 

Additionally, the premise of using the weight factor of 100 came from another paper which suggested a *static weight* of 100 for the initial conditions. So there was some basis for initializing the adaptive weights there - https://arxiv.org/pdf/2007.04542.pdf

This same paper shows the failure of the baseline PINN to solve the AC PDE in figure 3.1, for reference.
