### ISSUE TITLE
the problem in Helmholtz ntk

### ISSUE THREAD

**Issue by yujingyan222** [levimcclenny/SA-PINNs#6]
Dear @levimcclenny ,
Thanks for sharing the code, it is awesome. I have a question about helmholtz ntk, the uploaded code doesn't use ntk, could you please update the code? In addition, do you think I can use it to deal with the ultrasound data e.g. frequency = 5MHz. 
Thanks a lot

**Comment by levimcclenny** [comment]
SA-PINNs don't rely on calculating the NTK, closing this issue.

Yes as long as you have a system that includes the frequency in your model then sure. Without knowing specifics it's hard to say exactly how.
